name: warden
version: 1.5
main: me.codex.warden.Main
author: codex
commands:
  ban:
    description: Ban a player
  unban:
    description: Unban a player
  mute:
    description: Mute a player
  unmute:
    description: Unmute a player
  warden:
    description: Basic plugin commands
  lb:
    description: 'Block Logging'
    usage: 'Usage: /<command> help'
    aliases: logblock
